const italic_data = {
    p_one : "(1): Sollten Sie nach der gratis Revision eine weitere Revision benötigen, die nicht durch uns verschuldet wurde, führen wir diese standardmässig für 50 % des Nettopreises pro Visualisierung durch. Unsere effizienten Prozesse und die sehr hohe Qualität führen jedoch dazu, dass in der Regel eine einzige Revision ausreicht: In hunderten von Projekten benötigen unsere Kunden nur in 6 % aller Fälle eine zusätzliche Revision, und auch dann meist nur, wenn sich die Pläne nachträglich deutlich geändert haben.",
    p_two : "Bitte beachten Sie: Bei Änderungen der Pläne (unabhängig davon, ob diese im Rahmen der gratis oder einer zusätzlichen Revision erfolgen) wird der Preis je nach Umfang der Veränderungen individuell festgelegt. Je nach Umfang dauert eine Revision mindestens 50 % der ursprünglichen Lieferzeit.",
    p_three: "(2): Sollten Sie nach 12 Monaten die Tour immer noch benutzen möchten, können Sie gerne eine Verlängerung des Hostings um weitere 12 Monate optional für 50,00 € beauftragen.\n\n",
    p_four: "Haftungsausschluss: Wir sind stets bestrebt, Ihre Visualisierungen so detailgetreu wie möglich zu erstellen. Jedoch dienen die Visualisierungen nur der Veranschaulichung. Folglich wird keine Haftung für eventuelle Schäden auf Grund von Abweichungen übernommen.",
    p_five: "Nutzungsrecht: Die Nutzung der durch uns erstellten Visualisierungen ist erst nach Zahlung gestattet.",
    p_six: "Es gelten unsere allgemeinen Verkaufs- und Lieferbedingungen. Die gültige Version der allgemeinen Verkaufs- und Lieferbedingungen Stand 03/2023 finden Sie auf der Website: https://www.exposeprofi.de/agb. Außerdem auf Anforderung erhältlich.",
    p_seven: "Nach der ersten vollständigen Lieferung aller bestellten Produkte wird das Projekt in Rechnung gestellt. Die im Angebot inbegriffene kostenlose Revision können Sie jederzeit in Anspruch nehmen.",
    p_eight: "Damit wir Ihr Projekt zügig und planbar umsetzen können, reservieren wir feste Kapazitäten. Wenn Sie die vollständigen Unterlagen entgegen Ihrer ursprünglichen Planung nicht innerhalb von 30 Tagen nach Angebotsannahme einreichen können, bleibt Ihr Auftrag selbstverständlich erhalten. Wir wandeln ihn dann einfach in eine Gutscheinrechnung um. Der Gutschein ist 12 Monate gültig und kann flexibel für Visualisierungen des Objektes eingesetzt werden."
};

module.exports = italic_data;